name: Deploy

on:
  push:
    paths:
      - "public/blogs/*.md"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Switch to pull request branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get list of dates from updated markdown files
        run: |
          git diff --name-only HEAD~1 -- 'public/blogs/*.md' | sed -e 's/public\/blogs\/\([0-9-]*\)\.md/\1/' > changed_dates.txt

      - name: Check if there are updated markdown files
        id: check_files
        run: |
          if [ ! -s changed_dates.txt ]; then
            echo "No updated markdown files found, skipping."
            echo "skip=true" >> $GITHUB_ENV
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install

      - name: Generate comment
        run: |
          node ./scripts/generateComment.js ${{ secrets.OPENAI_API_KEY }} comment
          node ./scripts/generateComment.js ${{ secrets.OPENAI_API_KEY }} tarot

      - name: Commit changes
        run: |
          git config --local user.email "27812830+himanushi@users.noreply.github.com"
          git config --local user.name "himanushi"
          git add public/comments/
          git diff --cached --quiet || git commit -m "Auto-generated comments for updated blogs"
          git push

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
