name: Generate Comment
on:
  push:
    paths:
      - "public/blogs/*.md"

jobs:
  generate-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        run: |
          git diff --name-only HEAD~1 -- 'public/blogs/*.md' | sed -e 's/public\/blogs\/\([0-9-]*\)\.md/\1/' > changed_dates.txt

      # - name: Get list of dates from updated markdown files
      #   run: |
      #     git diff --name-only HEAD~1 -- 'public/blogs/*.md' | sed -e 's/public\/blogs\/\([0-9-]*\)\.md/\1/' > changed_dates.txt

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install

      - name: Generate comment
        run: |
          node ./scripts/generateComment.js ${{ secrets.OPENAI_API_KEY }} comment

      - name: Commit changes
        run: |
          git config --local user.email "27812830+himanushi@users.noreply.github.com"
          git config --local user.name "himanushi"
          git add public/blogs/
          git commit -m "Auto-generated comments for updated blogs"
          git push
